# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go package

on:
  push:
    branches: 
      - main

jobs:
  build:
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/github.com/${{ github.repository }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.GOPATH }}/github.com/${{ github.repository }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Install dependencies
        run: |
          sudo apt-get install make gcc libpq-dev libssl-dev libxml2-dev pkg-config liblz4-dev libzstd-dev libbz2-dev libz-dev
          go get .

      - name: Build
        run: go build -v ./...

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: go-rt_linux
          path: ./bin/go-rt

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        uses: technote-space/release-github-actions@v6
