# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go package

on:
  push:
    branches: 
      - main

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: go-rt_linux
          path: ./bin/go-rt

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        uses: technote-space/release-github-actions@v6

  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: go-rt_windows.exe
          path: ./bin/go-rt.exe

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        uses: technote-space/release-github-actions@v6

  mac-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: go-rt_macos
          path: ./bin/go-rt

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        uses: technote-space/release-github-actions@v6
